# Generated by Django 4.2 on 2025-11-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='movie_videos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
