# Generated by Django 4.2 on 2025-11-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_watchlater_watchhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'movie')},
        ),
    ]
